CREATE TABLE user (
    id INT AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    organization_name VARCHAR(255)  NULL,
    phone VARCHAR(20),
    type ENUM('ORGANIZATION', 'PROFESSOR', 'ADMIN') NOT NULL,
    password VARCHAR(255) NOT NULL,
    status ENUM('ACTIVE', 'PENDING', 'DELETED') NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(id)
);